repository:
  source:
    provider: github
  target:
    provider: bitbucket

github:
  username: svartoS
  accessToken: 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
  api-url: https://api.github.com

bitbucket:
  username: svarto666
  owner-name: svarto1
  password: ATBBFWk96bTL5JzUpRezxpTqESdEA4F4F99D
  api-url: https://api.bitbucket.org/2.0

