spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

github:
  username: svartoS
  accessToken: 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
  api-url: https://api.github.com

bitbucket:
    username: svarto666
    owner-name: svarto1
    password: ATBBjBBckCFFnKzX8JzuEYXVynZjD3664B01
    api-url: https://api.bitbucket.org/2.0


git:
  remote:
    path: C:/idc